"""
lektor.application.ports.container_ports
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Structural contract for the dependency injection container (IoC Container Protocol).
"""

from typing import Optional, Protocol

from ...domain.audio_models import CodeMode
from ...domain.normalization import TextNormalizationService
from ..ports.audio_ports import (
    AudioCacheProtocol,
    AudioCleanerProtocol,
    AudioStitcherProtocol,
    TTSEngineProtocol,
    VoiceDiscoveryProtocol,
)
from ..ports.ocr_ports import (
    PdfSplitterProtocol,
    VisionTranslatorProtocol,
)
from ..ports.resource_ports import AIModelArbiterProtocol
from ..ports.storage_ports import (
    BookRepositoryProtocol,
    NotesRepositoryProtocol,
    PageRepositoryProtocol,
    StudioHistoryRepositoryProtocol,
)
from ..ports.telemetry_ports import (
    GpuTelemetryProtocol,
    JobStatusProviderProtocol,
    ProgressReporterProtocol,
    TelemetryBroadcasterProtocol,
)
from ..use_cases.batch_synthesis import BatchSynthesisUseCase
from ..use_cases.convert_book import ConvertBookUseCase
from ..use_cases.convert_pdf_book import ConvertPdfBookUseCase
from ..use_cases.get_book_status import GetBookStatusUseCase
from ..use_cases.import_pdf_book import ImportPdfBookUseCase
from ..use_cases.list_books import ListBooksUseCase
from ..use_cases.preview_page import PreviewPageUseCase
from ..use_cases.render_pdf_scans import RenderPdfScansUseCase
from ..use_cases.render_scans_stream import RenderPdfScansStreamUseCase
from ..use_cases.switch_active_book import SwitchActiveBookUseCase
from ..use_cases.synthesize_page import SynthesizePageUseCase
from ..use_cases.synthesize_snippet import SynthesizeMarkdownSnippetUseCase


class ApplicationContainerProtocol(Protocol):
    def shutdown(self) -> None: ...
    def get_book_repository(self) -> BookRepositoryProtocol: ...
    def get_notes_repository(self) -> NotesRepositoryProtocol: ...
    def get_studio_history_repository(self) -> StudioHistoryRepositoryProtocol: ...
    def get_page_repository(self) -> PageRepositoryProtocol: ...
    def get_tts_engine(self) -> TTSEngineProtocol: ...
    def get_audio_stitcher(self) -> AudioStitcherProtocol: ...
    def get_audio_cleaner(self) -> AudioCleanerProtocol: ...
    def get_audio_cache(self) -> AudioCacheProtocol: ...
    def get_normalization_service(self) -> TextNormalizationService: ...
    def get_pdf_splitter(self) -> PdfSplitterProtocol: ...
    def get_vision_translator(self) -> VisionTranslatorProtocol: ...
    def get_telemetry_broadcaster(self) -> TelemetryBroadcasterProtocol: ...
    def get_gpu_telemetry(self) -> GpuTelemetryProtocol: ...
    def get_model_arbiter(self) -> AIModelArbiterProtocol: ...
    def get_voice_discovery(self) -> VoiceDiscoveryProtocol: ...
    def get_job_manager(self) -> JobStatusProviderProtocol: ...

    def create_preview_page_use_case(self, code_mode: CodeMode = "spoken") -> PreviewPageUseCase: ...
    def create_synthesize_snippet_use_case(self) -> SynthesizeMarkdownSnippetUseCase: ...
    def create_synthesize_page_use_case(
        self,
        tts_engine: Optional[TTSEngineProtocol] = None,
        model_arbiter: Optional[AIModelArbiterProtocol] = None,
    ) -> SynthesizePageUseCase: ...
    def create_batch_synthesis_use_case(
        self,
        synthesize_page_uc: Optional[SynthesizePageUseCase] = None,
        progress_reporter: Optional[ProgressReporterProtocol] = None,
    ) -> BatchSynthesisUseCase: ...
    def create_list_books_use_case(self) -> ListBooksUseCase: ...
    def create_switch_active_book_use_case(self) -> SwitchActiveBookUseCase: ...
    def create_import_pdf_book_use_case(self) -> ImportPdfBookUseCase: ...
    def create_convert_book_use_case(
        self,
        progress_reporter: Optional[ProgressReporterProtocol] = None,
        vision_translator: Optional[VisionTranslatorProtocol] = None,
    ) -> ConvertBookUseCase: ...
    def create_convert_pdf_book_use_case(self, model_name: Optional[str] = None) -> ConvertPdfBookUseCase: ...
    def create_render_scans_stream_use_case(self) -> RenderPdfScansStreamUseCase: ...
    def create_render_pdf_scans_use_case(self) -> RenderPdfScansUseCase: ...
    def create_get_book_status_use_case(self) -> GetBookStatusUseCase: ...

    def reset_book_context(self, new_paths: Optional[object] = None) -> None: ...