"""
lektor.application.ports.storage_ports
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Input/output ports for data persistence and repositories.
"""

from pathlib import Path
from typing import Protocol, Sequence

from ...domain.audio_models import SynthesisStats
from ...domain.book_models import Book, BookMetadata
from ...domain.conversion_models import DocumentScan
from ...domain.studio_models import StudioItem


class PageContentReaderProtocol(Protocol):
    def read_markdown(self, path: Path) -> str: ...
    def list_pages(self, directory: Path, pattern: str = "*.md") -> Sequence[Path]: ...
    def page_exists(self, path: Path, min_bytes: int = 0) -> bool: ...
    def get_page_size(self, path: Path) -> int: ...


class PageContentWriterProtocol(Protocol):
    def write_markdown(self, path: Path, content: str) -> None: ...
    def save_preview(self, path: Path, text: str) -> None: ...
    def save_state(self, path: Path, state_dict: dict[str, object] | SynthesisStats) -> None: ...


class PageMediaInspectorProtocol(Protocol):
    def audio_exists(self, path: Path, min_bytes: int = 1000) -> bool: ...


class PageRepositoryProtocol(
    PageContentReaderProtocol,
    PageContentWriterProtocol,
    PageMediaInspectorProtocol,
    Protocol,
):
    ...


class BookReaderProtocol(Protocol):
    def get_book(self, slug_or_title: str) -> Book | None: ...
    def list_books(self) -> Sequence[Book]: ...
    def get_active_book(self) -> Book: ...
    def get_book_stats(self, slug: str) -> tuple[int, int, int]: ...
    def get_existing_scans(self, slug: str) -> Sequence[DocumentScan]: ...
    def pdf_exists(self, slug: str) -> bool: ...


class BookWriterProtocol(Protocol):
    def set_active_book(self, slug: str) -> Book: ...
    def save_metadata(self, slug: str, metadata: BookMetadata) -> None: ...
    def create_book(
        self,
        title: str,
        slug: str,
        author: str = "",
        language: str = "pl",
        description: str = "",
    ) -> Book: ...
    def save_pdf(self, slug: str, filename: str, content: bytes) -> Path: ...


class BookRepositoryProtocol(BookReaderProtocol, BookWriterProtocol, Protocol):
    ...


class NotesRepositoryProtocol(Protocol):
    def get_note(self, note_id: str) -> str: ...
    def save_note(self, note_id: str, content: str) -> Path: ...


class StudioHistoryRepositoryProtocol(Protocol):
    def get_history(self) -> Sequence[StudioItem]: ...
    def save_history(self, items: Sequence[StudioItem | dict[str, object]]) -> None: ...
    def add_or_update_item(self, item: StudioItem | dict[str, object]) -> None: ...
    def delete_item(self, item_id: str) -> bool: ...